Multiple MIG feature added
otwld/ollama-helm pull request #86
Opened 2024-08-12 15:29 UTC by JBleher

**Summary of changes:**
- Added the possibility to use several MIGs with one pod.
**Checklist:**
I don't know what to change in the _Chart.yml_ for artifacthub.io/changes ??
* [ ] I updated the `artifacthub.io/changes` in _Chart.yml_

2024-08-13 21:58 UTC, jdetroyes commented
Hi @JBleher 

We will take your request soon for MIG!

2024-08-15 11:40 UTC, jdetroyes requested changes
Hello @JBleher 

Can you check these changes.

2024-08-15 11:40 UTC, jdetroyes commented on templates/deployment.yaml
>          {{- end }}
It should only have two closing tags

2024-08-15 11:40 UTC, jdetroyes commented on templates/deployment.yaml
> -{{- end }}
And this one should not be removed

2024-08-15 15:02 UTC, JBleher commented on templates/deployment.yaml
> -{{- end }}
Thank you yes. Good catch. I will.

2024-08-17 11:17 UTC, JBleher commented
@jdetroyes corrected the template. Also changed the inserted part in the values to an empty list, since that caued problems in my particular implementation.

2024-08-17 11:21 UTC, JBleher commented
Also: I don't understand the error code in the CI pipeline? Sorry... would fix it, but I don't know what causes it...

------------------------------------------------------------------------------------------------------------------------

 ✖︎ ollama => (version: "0.53.0", path: ".") > failed waiting for process: exit status 1

------------------------------------------------------------------------------------------------------------------------

failed linting and installing charts: failed processing charts

Error: failed linting and installing charts: failed processing charts

2024-08-18 13:56 UTC, jdetroyes requested changes
Hey @JBleher 

One last thing before we merge, can you please check the default value change I mentioned.

2024-08-18 13:56 UTC, jdetroyes commented on values.yaml
> +      devices: []
It should be `{}` as it's a map not an array.

2024-08-28 11:24 UTC, jdetroyes approved these changes

2024-08-28 11:25 UTC, merged